---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Stuffer
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Email::MIME: 1.901
  Email::Sender: 1.300000
  Email::Simple: 1.998
  File::Basename: 0
  File::Type: 0.22
  Params::Util: 1.05
  prefork: 1.01
version: 0.002
